version: '3'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=prod
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "3"
  callback_order_status:
    build: .
    environment:
      - CMD=callbackOrderStatus
      - NODE_ENV=prod
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "3"
